#[derive(thiserror::Error, Debug)]
pub enum CountryError {
    #[error("Nonexistent Country")]
    NonexistentCountry,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Country {
    Japan,
    Antarctica,
    CaribbeanNetherlands,
    FalklandIslands,
    Scotland,
    Wales,
    SintMaarten,
    Anguilla,
    AntiguaAndBarbuda,
    Argentina,
    Aruba,
    Bahamas,
    Barbados,
    Belize,
    Bolivia,
    Brazil,
    BritishVirginIslands,
    Canada,
    CaymanIslands,
    Chile,
    Colombia,
    CostaRica,
    Dominica,
    DominicanRepublic,
    Ecuador,
    ElSalvador,
    FrenchGuiana,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guyana,
    Haiti,
    Honduras,
    Jamaica,
    Martinique,
    Mexico,
    Montserrat,
    Curacao,
    Nicaragua,
    Panama,
    Paraguay,
    Peru,
    StKittsAndNevis,
    StLucia,
    StVincentAndTheGrenadines,
    Suriname,
    TrinidadAndTobago,
    TurksAndCaicosIslands,
    UnitedStates,
    Uruguay,
    USVirginIslands,
    Venezuela,
    Armenia,
    Belarus,
    Georgia,
    Kosovo,
    Abkhazia,
    Catalonia,
    England,
    SouthOssetia,
    Bougainville,
    Aland,
    FaroeIslands,
    Albania,
    Australia,
    Austria,
    Belgium,
    BosniaAndHerzegovina,
    Botswana,
    Bulgaria,
    Croatia,
    Cyprus,
    Czechia,
    Denmark,
    Estonia,
    Finland,
    France,
    Germany,
    Greece,
    Hungary,
    Iceland,
    Ireland,
    Italy,
    Latvia,
    Lesotho,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    NorthMacedonia,
    Malta,
    Montenegro,
    Mozambique,
    Namibia,
    Netherlands,
    NewZealand,
    Norway,
    Poland,
    Portugal,
    Romania,
    Russia,
    Serbia,
    Slovakia,
    Slovenia,
    SouthAfrica,
    Spain,
    Eswatini,
    Sweden,
    Switzerland,
    Turkey,
    UnitedKingdom,
    Zambia,
    Zimbabwe,
    Azerbaijan,
    Mauritania,
    Mali,
    Niger,
    Chad,
    Sudan,
    Eritrea,
    Djibouti,
    Somalia,
    Andorra,
    Gibraltar,
    Guernsey,
    IsleOfMan,
    Jersey,
    Monaco,
    Taiwan,
    Cambodia,
    Laos,
    Mongolia,
    Myanmar,
    Nepal,
    Vietnam,
    NorthKorea,
    SouthKorea,
    Bangladesh,
    Bhutan,
    Brunei,
    Maldives,
    SriLanka,
    TimorLeste,
    BritishIndianOceanTerritory,
    HongKong,
    Macao,
    CookIslands,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    AmericanSamoa,
    Guam,
    Indonesia,
    Singapore,
    Thailand,
    Philippines,
    Malaysia,
    SaintBarthelemy,
    SaintMartin,
    SaintPierreAndMiquelon,
    China,
    Afghanistan,
    Kazakhstan,
    Kyrgyzstan,
    Pakistan,
    Tajikistan,
    Turkmenistan,
    Uzbekistan,
    UAE,
    India,
    Egypt,
    Oman,
    Qatar,
    Kuwait,
    SaudiArabia,
    Syria,
    Bahrain,
    Jordan,
    Iran,
    Iraq,
    Israel,
    Lebanon,
    StateOfPalestine,
    Yemen,
    SanMarino,
    VaticanCity,
    Bermuda,
    FrenchPolynesia,
    Reunion,
    Mayotte,
    NewCaledonia,
    WallisAndFutuna,
    Nigeria,
    Angola,
    Ghana,
    Togo,
    Benin,
    BurkinaFaso,
    CoteDIvoire,
    Liberia,
    SierraLeone,
    Guinea,
    GuineaBissau,
    Senegal,
    TheGambia,
    CapeVerde,
    SaintHelenaAscensionAndTristanDaCunha,
    Moldova,
    Ukraine,
    Cameroon,
    CentralAfricanRepublic,
    DemocraticRepublicOfTheCongo,
    RepublicOfTheCongo,
    EquatorialGuinea,
    Gabon,
    SaoTomeAndPrincipe,
    Algeria,
    Ethiopia,
    Libya,
    Morocco,
    SouthSudan,
    Tunisia,
    SahrawiArabDemocraticRepublic,
    Cuba,
    Burundi,
    Comoros,
    Kenya,
    Madagascar,
    Malawi,
    Mauritius,
    Rwanda,
    Seychelles,
    Tanzania,
    Uganda,
    FrenchSouthernAndAntarcticLands,
    PitcairnIslands,
    BritishAntarcticTerritory,
    SouthGeorgiaAndTheSouthSandwichIslands,
    FederatedStatesOfMicronesia,
    Fiji,
    Kiribati,
    MarshallIslands,
    Nauru,
    Palau,
    PapuaNewGuinea,
    Samoa,
    SolomonIslands,
    Tokelau,
    Tonga,
    Tuvalu,
    Vanuatu,
    ChristmasIsland,
    CocosKeelingIslands,
    PuertoRico,
    Greenland,
    NotSet,
}

impl TryFrom<u8> for Country {
    type Error = CountryError;

    fn try_from(id: u8) -> Result<Self, Self::Error> {
        match id {
            0x01 => Ok(Country::Japan),
            0x02 => Ok(Country::Antarctica),
            0x03 => Ok(Country::CaribbeanNetherlands),
            0x04 => Ok(Country::FalklandIslands),
            0x05 => Ok(Country::Scotland),
            0x06 => Ok(Country::Wales),
            0x07 => Ok(Country::SintMaarten),
            0x08 => Ok(Country::Anguilla),
            0x09 => Ok(Country::AntiguaAndBarbuda),
            0x0A => Ok(Country::Argentina),
            0x0B => Ok(Country::Aruba),
            0x0C => Ok(Country::Bahamas),
            0x0D => Ok(Country::Barbados),
            0x0E => Ok(Country::Belize),
            0x0F => Ok(Country::Bolivia),
            0x10 => Ok(Country::Brazil),
            0x11 => Ok(Country::BritishVirginIslands),
            0x12 => Ok(Country::Canada),
            0x13 => Ok(Country::CaymanIslands),
            0x14 => Ok(Country::Chile),
            0x15 => Ok(Country::Colombia),
            0x16 => Ok(Country::CostaRica),
            0x17 => Ok(Country::Dominica),
            0x18 => Ok(Country::DominicanRepublic),
            0x19 => Ok(Country::Ecuador),
            0x1A => Ok(Country::ElSalvador),
            0x1B => Ok(Country::FrenchGuiana),
            0x1C => Ok(Country::Grenada),
            0x1D => Ok(Country::Guadeloupe),
            0x1E => Ok(Country::Guatemala),
            0x1F => Ok(Country::Guyana),
            0x20 => Ok(Country::Haiti),
            0x21 => Ok(Country::Honduras),
            0x22 => Ok(Country::Jamaica),
            0x23 => Ok(Country::Martinique),
            0x24 => Ok(Country::Mexico),
            0x25 => Ok(Country::Montserrat),
            0x26 => Ok(Country::Curacao),
            0x27 => Ok(Country::Nicaragua),
            0x28 => Ok(Country::Panama),
            0x29 => Ok(Country::Paraguay),
            0x2A => Ok(Country::Peru),
            0x2B => Ok(Country::StKittsAndNevis),
            0x2C => Ok(Country::StLucia),
            0x2D => Ok(Country::StVincentAndTheGrenadines),
            0x2E => Ok(Country::Suriname),
            0x2F => Ok(Country::TrinidadAndTobago),
            0x30 => Ok(Country::TurksAndCaicosIslands),
            0x31 => Ok(Country::UnitedStates),
            0x32 => Ok(Country::Uruguay),
            0x33 => Ok(Country::USVirginIslands),
            0x34 => Ok(Country::Venezuela),
            0x35 => Ok(Country::Armenia),
            0x36 => Ok(Country::Belarus),
            0x37 => Ok(Country::Georgia),
            0x38 => Ok(Country::Kosovo),
            0x39 => Ok(Country::Abkhazia),
            0x3A => Ok(Country::Catalonia),
            0x3B => Ok(Country::England),
            0x3C => Ok(Country::SouthOssetia),
            0x3D => Ok(Country::Bougainville),
            0x3E => Ok(Country::Aland),
            0x3F => Ok(Country::FaroeIslands),
            0x40 => Ok(Country::Albania),
            0x41 => Ok(Country::Australia),
            0x42 => Ok(Country::Austria),
            0x43 => Ok(Country::Belgium),
            0x44 => Ok(Country::BosniaAndHerzegovina),
            0x45 => Ok(Country::Botswana),
            0x46 => Ok(Country::Bulgaria),
            0x47 => Ok(Country::Croatia),
            0x48 => Ok(Country::Cyprus),
            0x49 => Ok(Country::Czechia),
            0x4A => Ok(Country::Denmark),
            0x4B => Ok(Country::Estonia),
            0x4C => Ok(Country::Finland),
            0x4D => Ok(Country::France),
            0x4E => Ok(Country::Germany),
            0x4F => Ok(Country::Greece),
            0x50 => Ok(Country::Hungary),
            0x51 => Ok(Country::Iceland),
            0x52 => Ok(Country::Ireland),
            0x53 => Ok(Country::Italy),
            0x54 => Ok(Country::Latvia),
            0x55 => Ok(Country::Lesotho),
            0x56 => Ok(Country::Liechtenstein),
            0x57 => Ok(Country::Lithuania),
            0x58 => Ok(Country::Luxembourg),
            0x59 => Ok(Country::NorthMacedonia),
            0x5A => Ok(Country::Malta),
            0x5B => Ok(Country::Montenegro),
            0x5C => Ok(Country::Mozambique),
            0x5D => Ok(Country::Namibia),
            0x5E => Ok(Country::Netherlands),
            0x5F => Ok(Country::NewZealand),
            0x60 => Ok(Country::Norway),
            0x61 => Ok(Country::Poland),
            0x62 => Ok(Country::Portugal),
            0x63 => Ok(Country::Romania),
            0x64 => Ok(Country::Russia),
            0x65 => Ok(Country::Serbia),
            0x66 => Ok(Country::Slovakia),
            0x67 => Ok(Country::Slovenia),
            0x68 => Ok(Country::SouthAfrica),
            0x69 => Ok(Country::Spain),
            0x6A => Ok(Country::Eswatini),
            0x6B => Ok(Country::Sweden),
            0x6C => Ok(Country::Switzerland),
            0x6D => Ok(Country::Turkey),
            0x6E => Ok(Country::UnitedKingdom),
            0x6F => Ok(Country::Zambia),
            0x70 => Ok(Country::Zimbabwe),
            0x71 => Ok(Country::Azerbaijan),
            0x72 => Ok(Country::Mauritania),
            0x73 => Ok(Country::Mali),
            0x74 => Ok(Country::Niger),
            0x75 => Ok(Country::Chad),
            0x76 => Ok(Country::Sudan),
            0x77 => Ok(Country::Eritrea),
            0x78 => Ok(Country::Djibouti),
            0x79 => Ok(Country::Somalia),
            0x7A => Ok(Country::Andorra),
            0x7B => Ok(Country::Gibraltar),
            0x7C => Ok(Country::Guernsey),
            0x7D => Ok(Country::IsleOfMan),
            0x7E => Ok(Country::Jersey),
            0x7F => Ok(Country::Monaco),
            0x80 => Ok(Country::Taiwan),
            0x81 => Ok(Country::Cambodia),
            0x82 => Ok(Country::Laos),
            0x83 => Ok(Country::Mongolia),
            0x84 => Ok(Country::Myanmar),
            0x85 => Ok(Country::Nepal),
            0x86 => Ok(Country::Vietnam),
            0x87 => Ok(Country::NorthKorea),
            0x88 => Ok(Country::SouthKorea),
            0x89 => Ok(Country::Bangladesh),
            0x8A => Ok(Country::Bhutan),
            0x8B => Ok(Country::Brunei),
            0x8C => Ok(Country::Maldives),
            0x8D => Ok(Country::SriLanka),
            0x8E => Ok(Country::TimorLeste),
            0x8F => Ok(Country::BritishIndianOceanTerritory),
            0x90 => Ok(Country::HongKong),
            0x91 => Ok(Country::Macao),
            0x92 => Ok(Country::CookIslands),
            0x93 => Ok(Country::Niue),
            0x94 => Ok(Country::NorfolkIsland),
            0x95 => Ok(Country::NorthernMarianaIslands),
            0x96 => Ok(Country::AmericanSamoa),
            0x97 => Ok(Country::Guam),
            0x98 => Ok(Country::Indonesia),
            0x99 => Ok(Country::Singapore),
            0x9A => Ok(Country::Thailand),
            0x9B => Ok(Country::Philippines),
            0x9C => Ok(Country::Malaysia),
            0x9D => Ok(Country::SaintBarthelemy),
            0x9E => Ok(Country::SaintMartin),
            0x9F => Ok(Country::SaintPierreAndMiquelon),
            0xA0 => Ok(Country::China),
            0xA1 => Ok(Country::Afghanistan),
            0xA2 => Ok(Country::Kazakhstan),
            0xA3 => Ok(Country::Kyrgyzstan),
            0xA4 => Ok(Country::Pakistan),
            0xA5 => Ok(Country::Tajikistan),
            0xA6 => Ok(Country::Turkmenistan),
            0xA7 => Ok(Country::Uzbekistan),
            0xA8 => Ok(Country::UAE),
            0xA9 => Ok(Country::India),
            0xAA => Ok(Country::Egypt),
            0xAB => Ok(Country::Oman),
            0xAC => Ok(Country::Qatar),
            0xAD => Ok(Country::Kuwait),
            0xAE => Ok(Country::SaudiArabia),
            0xAF => Ok(Country::Syria),
            0xB0 => Ok(Country::Bahrain),
            0xB1 => Ok(Country::Jordan),
            0xB2 => Ok(Country::Iran),
            0xB3 => Ok(Country::Iraq),
            0xB4 => Ok(Country::Israel),
            0xB5 => Ok(Country::Lebanon),
            0xB6 => Ok(Country::StateOfPalestine),
            0xB7 => Ok(Country::Yemen),
            0xB8 => Ok(Country::SanMarino),
            0xB9 => Ok(Country::VaticanCity),
            0xBA => Ok(Country::Bermuda),
            0xBB => Ok(Country::FrenchPolynesia),
            0xBC => Ok(Country::Reunion),
            0xBD => Ok(Country::Mayotte),
            0xBE => Ok(Country::NewCaledonia),
            0xBF => Ok(Country::WallisAndFutuna),
            0xC0 => Ok(Country::Nigeria),
            0xC1 => Ok(Country::Angola),
            0xC2 => Ok(Country::Ghana),
            0xC3 => Ok(Country::Togo),
            0xC4 => Ok(Country::Benin),
            0xC5 => Ok(Country::BurkinaFaso),
            0xC6 => Ok(Country::CoteDIvoire),
            0xC7 => Ok(Country::Liberia),
            0xC8 => Ok(Country::SierraLeone),
            0xC9 => Ok(Country::Guinea),
            0xCA => Ok(Country::GuineaBissau),
            0xCB => Ok(Country::Senegal),
            0xCC => Ok(Country::TheGambia),
            0xCD => Ok(Country::CapeVerde),
            0xCE => Ok(Country::SaintHelenaAscensionAndTristanDaCunha),
            0xCF => Ok(Country::Moldova),
            0xD0 => Ok(Country::Ukraine),
            0xD1 => Ok(Country::Cameroon),
            0xD2 => Ok(Country::CentralAfricanRepublic),
            0xD3 => Ok(Country::DemocraticRepublicOfTheCongo),
            0xD4 => Ok(Country::RepublicOfTheCongo),
            0xD5 => Ok(Country::EquatorialGuinea),
            0xD6 => Ok(Country::Gabon),
            0xD7 => Ok(Country::SaoTomeAndPrincipe),
            0xD8 => Ok(Country::Algeria),
            0xD9 => Ok(Country::Ethiopia),
            0xDA => Ok(Country::Libya),
            0xDB => Ok(Country::Morocco),
            0xDC => Ok(Country::SouthSudan),
            0xDD => Ok(Country::Tunisia),
            0xDE => Ok(Country::SahrawiArabDemocraticRepublic),
            0xDF => Ok(Country::Cuba),
            0xE0 => Ok(Country::Burundi),
            0xE1 => Ok(Country::Comoros),
            0xE2 => Ok(Country::Kenya),
            0xE3 => Ok(Country::Madagascar),
            0xE4 => Ok(Country::Malawi),
            0xE5 => Ok(Country::Mauritius),
            0xE6 => Ok(Country::Rwanda),
            0xE7 => Ok(Country::Seychelles),
            0xE8 => Ok(Country::Tanzania),
            0xE9 => Ok(Country::Uganda),
            0xEA => Ok(Country::FrenchSouthernAndAntarcticLands),
            0xEB => Ok(Country::PitcairnIslands),
            0xEC => Ok(Country::BritishAntarcticTerritory),
            0xED => Ok(Country::SouthGeorgiaAndTheSouthSandwichIslands),
            0xEE => Ok(Country::FederatedStatesOfMicronesia),
            0xEF => Ok(Country::Fiji),
            0xF0 => Ok(Country::Kiribati),
            0xF1 => Ok(Country::MarshallIslands),
            0xF2 => Ok(Country::Nauru),
            0xF3 => Ok(Country::Palau),
            0xF4 => Ok(Country::PapuaNewGuinea),
            0xF5 => Ok(Country::Samoa),
            0xF6 => Ok(Country::SolomonIslands),
            0xF7 => Ok(Country::Tokelau),
            0xF8 => Ok(Country::Tonga),
            0xF9 => Ok(Country::Tuvalu),
            0xFA => Ok(Country::Vanuatu),
            0xFB => Ok(Country::ChristmasIsland),
            0xFC => Ok(Country::CocosKeelingIslands),
            0xFD => Ok(Country::PuertoRico),
            0xFE => Ok(Country::Greenland),
            0xFF => Ok(Country::NotSet),
            _ => Err(Self::Error::NonexistentCountry),
        }
    }
}

impl From<Country> for u8 {
    fn from(value: Country) -> Self {
        match value {
            Country::Japan => 0x01,
            Country::Antarctica => 0x02,
            Country::CaribbeanNetherlands => 0x03,
            Country::FalklandIslands => 0x04,
            Country::Scotland => 0x05,
            Country::Wales => 0x06,
            Country::SintMaarten => 0x07,
            Country::Anguilla => 0x08,
            Country::AntiguaAndBarbuda => 0x09,
            Country::Argentina => 0x0A,
            Country::Aruba => 0x0B,
            Country::Bahamas => 0x0C,
            Country::Barbados => 0x0D,
            Country::Belize => 0x0E,
            Country::Bolivia => 0x0F,
            Country::Brazil => 0x10,
            Country::BritishVirginIslands => 0x11,
            Country::Canada => 0x12,
            Country::CaymanIslands => 0x13,
            Country::Chile => 0x14,
            Country::Colombia => 0x15,
            Country::CostaRica => 0x16,
            Country::Dominica => 0x17,
            Country::DominicanRepublic => 0x18,
            Country::Ecuador => 0x19,
            Country::ElSalvador => 0x1A,
            Country::FrenchGuiana => 0x1B,
            Country::Grenada => 0x1C,
            Country::Guadeloupe => 0x1D,
            Country::Guatemala => 0x1E,
            Country::Guyana => 0x1F,
            Country::Haiti => 0x20,
            Country::Honduras => 0x21,
            Country::Jamaica => 0x22,
            Country::Martinique => 0x23,
            Country::Mexico => 0x24,
            Country::Montserrat => 0x25,
            Country::Curacao => 0x26,
            Country::Nicaragua => 0x27,
            Country::Panama => 0x28,
            Country::Paraguay => 0x29,
            Country::Peru => 0x2A,
            Country::StKittsAndNevis => 0x2B,
            Country::StLucia => 0x2C,
            Country::StVincentAndTheGrenadines => 0x2D,
            Country::Suriname => 0x2E,
            Country::TrinidadAndTobago => 0x2F,
            Country::TurksAndCaicosIslands => 0x30,
            Country::UnitedStates => 0x31,
            Country::Uruguay => 0x32,
            Country::USVirginIslands => 0x33,
            Country::Venezuela => 0x34,
            Country::Armenia => 0x35,
            Country::Belarus => 0x36,
            Country::Georgia => 0x37,
            Country::Kosovo => 0x38,
            Country::Abkhazia => 0x39,
            Country::Catalonia => 0x3A,
            Country::England => 0x3B,
            Country::SouthOssetia => 0x3C,
            Country::Bougainville => 0x3D,
            Country::Aland => 0x3E,
            Country::FaroeIslands => 0x3F,
            Country::Albania => 0x40,
            Country::Australia => 0x41,
            Country::Austria => 0x42,
            Country::Belgium => 0x43,
            Country::BosniaAndHerzegovina => 0x44,
            Country::Botswana => 0x45,
            Country::Bulgaria => 0x46,
            Country::Croatia => 0x47,
            Country::Cyprus => 0x48,
            Country::Czechia => 0x49,
            Country::Denmark => 0x4A,
            Country::Estonia => 0x4B,
            Country::Finland => 0x4C,
            Country::France => 0x4D,
            Country::Germany => 0x4E,
            Country::Greece => 0x4F,
            Country::Hungary => 0x50,
            Country::Iceland => 0x51,
            Country::Ireland => 0x52,
            Country::Italy => 0x53,
            Country::Latvia => 0x54,
            Country::Lesotho => 0x55,
            Country::Liechtenstein => 0x56,
            Country::Lithuania => 0x57,
            Country::Luxembourg => 0x58,
            Country::NorthMacedonia => 0x59,
            Country::Malta => 0x5A,
            Country::Montenegro => 0x5B,
            Country::Mozambique => 0x5C,
            Country::Namibia => 0x5D,
            Country::Netherlands => 0x5E,
            Country::NewZealand => 0x5F,
            Country::Norway => 0x60,
            Country::Poland => 0x61,
            Country::Portugal => 0x62,
            Country::Romania => 0x63,
            Country::Russia => 0x64,
            Country::Serbia => 0x65,
            Country::Slovakia => 0x66,
            Country::Slovenia => 0x67,
            Country::SouthAfrica => 0x68,
            Country::Spain => 0x69,
            Country::Eswatini => 0x6A,
            Country::Sweden => 0x6B,
            Country::Switzerland => 0x6C,
            Country::Turkey => 0x6D,
            Country::UnitedKingdom => 0x6E,
            Country::Zambia => 0x6F,
            Country::Zimbabwe => 0x70,
            Country::Azerbaijan => 0x71,
            Country::Mauritania => 0x72,
            Country::Mali => 0x73,
            Country::Niger => 0x74,
            Country::Chad => 0x75,
            Country::Sudan => 0x76,
            Country::Eritrea => 0x77,
            Country::Djibouti => 0x78,
            Country::Somalia => 0x79,
            Country::Andorra => 0x7A,
            Country::Gibraltar => 0x7B,
            Country::Guernsey => 0x7C,
            Country::IsleOfMan => 0x7D,
            Country::Jersey => 0x7E,
            Country::Monaco => 0x7F,
            Country::Taiwan => 0x80,
            Country::Cambodia => 0x81,
            Country::Laos => 0x82,
            Country::Mongolia => 0x83,
            Country::Myanmar => 0x84,
            Country::Nepal => 0x85,
            Country::Vietnam => 0x86,
            Country::NorthKorea => 0x87,
            Country::SouthKorea => 0x88,
            Country::Bangladesh => 0x89,
            Country::Bhutan => 0x8A,
            Country::Brunei => 0x8B,
            Country::Maldives => 0x8C,
            Country::SriLanka => 0x8D,
            Country::TimorLeste => 0x8E,
            Country::BritishIndianOceanTerritory => 0x8F,
            Country::HongKong => 0x90,
            Country::Macao => 0x91,
            Country::CookIslands => 0x92,
            Country::Niue => 0x93,
            Country::NorfolkIsland => 0x94,
            Country::NorthernMarianaIslands => 0x95,
            Country::AmericanSamoa => 0x96,
            Country::Guam => 0x97,
            Country::Indonesia => 0x98,
            Country::Singapore => 0x99,
            Country::Thailand => 0x9A,
            Country::Philippines => 0x9B,
            Country::Malaysia => 0x9C,
            Country::SaintBarthelemy => 0x9D,
            Country::SaintMartin => 0x9E,
            Country::SaintPierreAndMiquelon => 0x9F,
            Country::China => 0xA0,
            Country::Afghanistan => 0xA1,
            Country::Kazakhstan => 0xA2,
            Country::Kyrgyzstan => 0xA3,
            Country::Pakistan => 0xA4,
            Country::Tajikistan => 0xA5,
            Country::Turkmenistan => 0xA6,
            Country::Uzbekistan => 0xA7,
            Country::UAE => 0xA8,
            Country::India => 0xA9,
            Country::Egypt => 0xAA,
            Country::Oman => 0xAB,
            Country::Qatar => 0xAC,
            Country::Kuwait => 0xAD,
            Country::SaudiArabia => 0xAE,
            Country::Syria => 0xAF,
            Country::Bahrain => 0xB0,
            Country::Jordan => 0xB1,
            Country::Iran => 0xB2,
            Country::Iraq => 0xB3,
            Country::Israel => 0xB4,
            Country::Lebanon => 0xB5,
            Country::StateOfPalestine => 0xB6,
            Country::Yemen => 0xB7,
            Country::SanMarino => 0xB8,
            Country::VaticanCity => 0xB9,
            Country::Bermuda => 0xBA,
            Country::FrenchPolynesia => 0xBB,
            Country::Reunion => 0xBC,
            Country::Mayotte => 0xBD,
            Country::NewCaledonia => 0xBE,
            Country::WallisAndFutuna => 0xBF,
            Country::Nigeria => 0xC0,
            Country::Angola => 0xC1,
            Country::Ghana => 0xC2,
            Country::Togo => 0xC3,
            Country::Benin => 0xC4,
            Country::BurkinaFaso => 0xC5,
            Country::CoteDIvoire => 0xC6,
            Country::Liberia => 0xC7,
            Country::SierraLeone => 0xC8,
            Country::Guinea => 0xC9,
            Country::GuineaBissau => 0xCA,
            Country::Senegal => 0xCB,
            Country::TheGambia => 0xCC,
            Country::CapeVerde => 0xCD,
            Country::SaintHelenaAscensionAndTristanDaCunha => 0xCE,
            Country::Moldova => 0xCF,
            Country::Ukraine => 0xD0,
            Country::Cameroon => 0xD1,
            Country::CentralAfricanRepublic => 0xD2,
            Country::DemocraticRepublicOfTheCongo => 0xD3,
            Country::RepublicOfTheCongo => 0xD4,
            Country::EquatorialGuinea => 0xD5,
            Country::Gabon => 0xD6,
            Country::SaoTomeAndPrincipe => 0xD7,
            Country::Algeria => 0xD8,
            Country::Ethiopia => 0xD9,
            Country::Libya => 0xDA,
            Country::Morocco => 0xDB,
            Country::SouthSudan => 0xDC,
            Country::Tunisia => 0xDD,
            Country::SahrawiArabDemocraticRepublic => 0xDE,
            Country::Cuba => 0xDF,
            Country::Burundi => 0xE0,
            Country::Comoros => 0xE1,
            Country::Kenya => 0xE2,
            Country::Madagascar => 0xE3,
            Country::Malawi => 0xE4,
            Country::Mauritius => 0xE5,
            Country::Rwanda => 0xE6,
            Country::Seychelles => 0xE7,
            Country::Tanzania => 0xE8,
            Country::Uganda => 0xE9,
            Country::FrenchSouthernAndAntarcticLands => 0xEA,
            Country::PitcairnIslands => 0xEB,
            Country::BritishAntarcticTerritory => 0xEC,
            Country::SouthGeorgiaAndTheSouthSandwichIslands => 0xED,
            Country::FederatedStatesOfMicronesia => 0xEE,
            Country::Fiji => 0xEF,
            Country::Kiribati => 0xF0,
            Country::MarshallIslands => 0xF1,
            Country::Nauru => 0xF2,
            Country::Palau => 0xF3,
            Country::PapuaNewGuinea => 0xF4,
            Country::Samoa => 0xF5,
            Country::SolomonIslands => 0xF6,
            Country::Tokelau => 0xF7,
            Country::Tonga => 0xF8,
            Country::Tuvalu => 0xF9,
            Country::Vanuatu => 0xFA,
            Country::ChristmasIsland => 0xFB,
            Country::CocosKeelingIslands => 0xFC,
            Country::PuertoRico => 0xFD,
            Country::Greenland => 0xFE,
            Country::NotSet => 0xFF,
        }
    }
}

impl std::fmt::Display for Country {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            Country::Japan => "Japan",
            Country::Antarctica => "Antarctica",
            Country::CaribbeanNetherlands => "Caribbean Netherlands",
            Country::FalklandIslands => "Falkland Islands",
            Country::Scotland => "Scotland",
            Country::Wales => "Wales",
            Country::SintMaarten => "Sint Maarten",
            Country::Anguilla => "Anguilla",
            Country::AntiguaAndBarbuda => "Antigua and Barbuda",
            Country::Argentina => "Argentina",
            Country::Aruba => "Aruba",
            Country::Bahamas => "Bahamas",
            Country::Barbados => "Barbados",
            Country::Belize => "Belize",
            Country::Bolivia => "Bolivia",
            Country::Brazil => "Brazil",
            Country::BritishVirginIslands => "British Virgin Islands",
            Country::Canada => "Canada",
            Country::CaymanIslands => "Cayman Islands",
            Country::Chile => "Chile",
            Country::Colombia => "Colombia",
            Country::CostaRica => "Costa Rica",
            Country::Dominica => "Dominica",
            Country::DominicanRepublic => "Dominican Republic",
            Country::Ecuador => "Ecuador",
            Country::ElSalvador => "El Salvador",
            Country::FrenchGuiana => "French Guiana",
            Country::Grenada => "Grenada",
            Country::Guadeloupe => "Guadeloupe",
            Country::Guatemala => "Guatemala",
            Country::Guyana => "Guyana",
            Country::Haiti => "Haiti",
            Country::Honduras => "Honduras",
            Country::Jamaica => "Jamaica",
            Country::Martinique => "Martinique",
            Country::Mexico => "Mexico",
            Country::Montserrat => "Montserrat",
            Country::Curacao => "Curaçao",
            Country::Nicaragua => "Nicaragua",
            Country::Panama => "Panama",
            Country::Paraguay => "Paraguay",
            Country::Peru => "Peru",
            Country::StKittsAndNevis => "St. Kitts and Nevis",
            Country::StLucia => "St. Lucia",
            Country::StVincentAndTheGrenadines => "St. Vincent and the Grenadines",
            Country::Suriname => "Suriname",
            Country::TrinidadAndTobago => "Trinidad and Tobago",
            Country::TurksAndCaicosIslands => "Turks and Caicos Islands",
            Country::UnitedStates => "United States",
            Country::Uruguay => "Uruguay",
            Country::USVirginIslands => "US Virgin Islands",
            Country::Venezuela => "Venezuela",
            Country::Armenia => "Armenia",
            Country::Belarus => "Belarus",
            Country::Georgia => "Georgia",
            Country::Kosovo => "Kosovo",
            Country::Abkhazia => "Abkhazia",
            Country::Catalonia => "Catalonia",
            Country::England => "England",
            Country::SouthOssetia => "South Ossetia",
            Country::Bougainville => "Bougainville",
            Country::Aland => "Åland",
            Country::FaroeIslands => "Faroe Islands",
            Country::Albania => "Albania",
            Country::Australia => "Australia",
            Country::Austria => "Austria",
            Country::Belgium => "Belgium",
            Country::BosniaAndHerzegovina => "Bosnia & Herzegovina",
            Country::Botswana => "Botswana",
            Country::Bulgaria => "Bulgaria",
            Country::Croatia => "Croatia",
            Country::Cyprus => "Cyprus",
            Country::Czechia => "Czechia",
            Country::Denmark => "Denmark",
            Country::Estonia => "Estonia",
            Country::Finland => "Finland",
            Country::France => "France",
            Country::Germany => "Germany",
            Country::Greece => "Greece",
            Country::Hungary => "Hungary",
            Country::Iceland => "Iceland",
            Country::Ireland => "Ireland",
            Country::Italy => "Italy",
            Country::Latvia => "Latvia",
            Country::Lesotho => "Lesotho",
            Country::Liechtenstein => "Liechtenstein",
            Country::Lithuania => "Lithuania",
            Country::Luxembourg => "Luxembourg",
            Country::NorthMacedonia => "North Macedonia",
            Country::Malta => "Malta",
            Country::Montenegro => "Montenegro",
            Country::Mozambique => "Mozambique",
            Country::Namibia => "Namibia",
            Country::Netherlands => "Netherlands",
            Country::NewZealand => "New Zealand",
            Country::Norway => "Norway",
            Country::Poland => "Poland",
            Country::Portugal => "Portugal",
            Country::Romania => "Romania",
            Country::Russia => "Russia",
            Country::Serbia => "Serbia",
            Country::Slovakia => "Slovakia",
            Country::Slovenia => "Slovenia",
            Country::SouthAfrica => "South Africa",
            Country::Spain => "Spain",
            Country::Eswatini => "Eswatini",
            Country::Sweden => "Sweden",
            Country::Switzerland => "Switzerland",
            Country::Turkey => "Turkey",
            Country::UnitedKingdom => "United Kingdom",
            Country::Zambia => "Zambia",
            Country::Zimbabwe => "Zimbabwe",
            Country::Azerbaijan => "Azerbaijan",
            Country::Mauritania => "Mauritania",
            Country::Mali => "Mali",
            Country::Niger => "Niger",
            Country::Chad => "Chad",
            Country::Sudan => "Sudan",
            Country::Eritrea => "Eritrea",
            Country::Djibouti => "Djibouti",
            Country::Somalia => "Somalia",
            Country::Andorra => "Andorra",
            Country::Gibraltar => "Gibraltar",
            Country::Guernsey => "Guernsey",
            Country::IsleOfMan => "Isle of Man",
            Country::Jersey => "Jersey",
            Country::Monaco => "Monaco",
            Country::Taiwan => "Taiwan",
            Country::Cambodia => "Cambodia",
            Country::Laos => "Laos",
            Country::Mongolia => "Mongolia",
            Country::Myanmar => "Myanmar",
            Country::Nepal => "Nepal",
            Country::Vietnam => "Vietnam",
            Country::NorthKorea => "North Korea",
            Country::SouthKorea => "South Korea",
            Country::Bangladesh => "Bangladesh",
            Country::Bhutan => "Bhutan",
            Country::Brunei => "Brunei",
            Country::Maldives => "Maldives",
            Country::SriLanka => "Sri Lanka",
            Country::TimorLeste => "Timor-Leste",
            Country::BritishIndianOceanTerritory => "British Indian Ocean Territory",
            Country::HongKong => "Hong Kong",
            Country::Macao => "Macao",
            Country::CookIslands => "Cook Islands",
            Country::Niue => "Niue",
            Country::NorfolkIsland => "Norfolk Island",
            Country::NorthernMarianaIslands => "Northern Mariana Islands",
            Country::AmericanSamoa => "American Samoa",
            Country::Guam => "Guam",
            Country::Indonesia => "Indonesia",
            Country::Singapore => "Singapore",
            Country::Thailand => "Thailand",
            Country::Philippines => "Philippines",
            Country::Malaysia => "Malaysia",
            Country::SaintBarthelemy => "Saint Barthélemy",
            Country::SaintMartin => "Saint Martin",
            Country::SaintPierreAndMiquelon => "Saint Pierre and Miquelon",
            Country::China => "China",
            Country::Afghanistan => "Afghanistan",
            Country::Kazakhstan => "Kazakhstan",
            Country::Kyrgyzstan => "Kyrgyzstan",
            Country::Pakistan => "Pakistan",
            Country::Tajikistan => "Tajikistan",
            Country::Turkmenistan => "Turkmenistan",
            Country::Uzbekistan => "Uzbekistan",
            Country::UAE => "U.A.E",
            Country::India => "India",
            Country::Egypt => "Egypt",
            Country::Oman => "Oman",
            Country::Qatar => "Qatar",
            Country::Kuwait => "Kuwait",
            Country::SaudiArabia => "Saudi Arabia",
            Country::Syria => "Syria",
            Country::Bahrain => "Bahrain",
            Country::Jordan => "Jordan",
            Country::Iran => "Iran",
            Country::Iraq => "Iraq",
            Country::Israel => "Israel",
            Country::Lebanon => "Lebanon",
            Country::StateOfPalestine => "State of Palestine",
            Country::Yemen => "Yemen",
            Country::SanMarino => "San Marino",
            Country::VaticanCity => "Vatican City",
            Country::Bermuda => "Bermuda",
            Country::FrenchPolynesia => "French Polynesia",
            Country::Reunion => "Réunion",
            Country::Mayotte => "Mayotte",
            Country::NewCaledonia => "New Caledonia",
            Country::WallisAndFutuna => "Wallis and Futuna",
            Country::Nigeria => "Nigeria",
            Country::Angola => "Angola",
            Country::Ghana => "Ghana",
            Country::Togo => "Togo",
            Country::Benin => "Benin",
            Country::BurkinaFaso => "Burkina Faso",
            Country::CoteDIvoire => "Côte d'Ivoire",
            Country::Liberia => "Liberia",
            Country::SierraLeone => "Sierra Leone",
            Country::Guinea => "Guinea",
            Country::GuineaBissau => "Guinea-Bissau",
            Country::Senegal => "Senegal",
            Country::TheGambia => "The Gambia",
            Country::CapeVerde => "Cape Verde",
            Country::SaintHelenaAscensionAndTristanDaCunha => {
                "Saint Helena, Ascension and Tristan da Cunha"
            }
            Country::Moldova => "Moldova",
            Country::Ukraine => "Ukraine",
            Country::Cameroon => "Cameroon",
            Country::CentralAfricanRepublic => "Central African Republic",
            Country::DemocraticRepublicOfTheCongo => "Democratic Republic of the Congo",
            Country::RepublicOfTheCongo => "Republic of the Congo",
            Country::EquatorialGuinea => "Equatorial Guinea",
            Country::Gabon => "Gabon",
            Country::SaoTomeAndPrincipe => "São Tomé and Príncipe",
            Country::Algeria => "Algeria",
            Country::Ethiopia => "Ethiopia",
            Country::Libya => "Libya",
            Country::Morocco => "Morocco",
            Country::SouthSudan => "South Sudan",
            Country::Tunisia => "Tunisia",
            Country::SahrawiArabDemocraticRepublic => "Sahrawi Arab Democratic Republic",
            Country::Cuba => "Cuba",
            Country::Burundi => "Burundi",
            Country::Comoros => "Comoros",
            Country::Kenya => "Kenya",
            Country::Madagascar => "Madagascar",
            Country::Malawi => "Malawi",
            Country::Mauritius => "Mauritius",
            Country::Rwanda => "Rwanda",
            Country::Seychelles => "Seychelles",
            Country::Tanzania => "Tanzania",
            Country::Uganda => "Uganda",
            Country::FrenchSouthernAndAntarcticLands => "French Southern and Antarctic Lands",
            Country::PitcairnIslands => "Pitcairn Islands",
            Country::BritishAntarcticTerritory => "British Antarctic Territory",
            Country::SouthGeorgiaAndTheSouthSandwichIslands => {
                "South Georgia and the South Sandwich Islands"
            }
            Country::FederatedStatesOfMicronesia => "Federated States of Micronesia",
            Country::Fiji => "Fiji",
            Country::Kiribati => "Kiribati",
            Country::MarshallIslands => "Marshall Islands",
            Country::Nauru => "Nauru",
            Country::Palau => "Palau",
            Country::PapuaNewGuinea => "Papua New Guinea",
            Country::Samoa => "Samoa",
            Country::SolomonIslands => "Solomon Islands",
            Country::Tokelau => "Tokelau",
            Country::Tonga => "Tonga",
            Country::Tuvalu => "Tuvalu",
            Country::Vanuatu => "Vanuatu",
            Country::ChristmasIsland => "Christmas Island",
            Country::CocosKeelingIslands => "Cocos (Keeling) Islands",
            Country::PuertoRico => "Puerto Rico",
            Country::Greenland => "Greenland",
            Country::NotSet => "Not Set",
        };
        write!(f, "{}", name)
    }
}
