#[derive(thiserror::Error, Debug)]
pub enum CountryError {
    #[error("Nonexistent Country")]
    NonexistentCountry,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Country {
    Japan,
    Antarctica,
    Bonaire,
    FalklandIslands,
    Saba,
    SintEustatius,
    SintMaarten,
    Anguilla,
    AntiguaAndBarbuda,
    Argentina,
    Aruba,
    Bahamas,
    Barbados,
    Belize,
    Bolivia,
    Brazil,
    BritishVirginIslands,
    Canada,
    CaymanIslands,
    Chile,
    Colombia,
    CostaRica,
    Dominica,
    DominicanRepublic,
    Ecuador,
    ElSalvador,
    FrenchGuiana,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guyana,
    Haiti,
    Honduras,
    Jamaica,
    Martinique,
    Mexico,
    Montserrat,
    Curacao,
    Nicaragua,
    Panama,
    Paraguay,
    Peru,
    StKittsAndNevis,
    StLucia,
    StVincentAndTheGrenadines,
    Suriname,
    TrinidadAndTobago,
    TurksAndCaicosIslands,
    UnitedStates,
    Uruguay,
    USVirginIslands,
    Venezuela,
    Armenia,
    Belarus,
    Georgia,
    Kosovo,
    Abkhazia,
    Artsakh,
    NorthernCyprus,
    SouthOssetia,
    Transnistria,
    Aland,
    FaroeIslands,
    Albania,
    Australia,
    Austria,
    Belgium,
    BosniaAndHerzegovina,
    Botswana,
    Bulgaria,
    Croatia,
    Cyprus,
    Czechia,
    Denmark,
    Estonia,
    Finland,
    France,
    Germany,
    Greece,
    Hungary,
    Iceland,
    Ireland,
    Italy,
    Latvia,
    Lesotho,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    NorthMacedonia,
    Malta,
    Montenegro,
    Mozambique,
    Namibia,
    Netherlands,
    NewZealand,
    Norway,
    Poland,
    Portugal,
    Romania,
    Russia,
    Serbia,
    Slovakia,
    Slovenia,
    SouthAfrica,
    Spain,
    Eswatini,
    Sweden,
    Switzerland,
    Turkey,
    UnitedKingdom,
    Zambia,
    Zimbabwe,
    Azerbaijan,
    Mauritania,
    Mali,
    Niger,
    Chad,
    Sudan,
    Eritrea,
    Djibouti,
    Somalia,
    Andorra,
    Gibraltar,
    Guernsey,
    IsleOfMan,
    Jersey,
    Monaco,
    Taiwan,
    Cambodia,
    Laos,
    Mongolia,
    Myanmar,
    Nepal,
    Vietnam,
    NorthKorea,
    SouthKorea,
    Bangladesh,
    Bhutan,
    Brunei,
    Maldives,
    SriLanka,
    TimorLeste,
    BritishIndianOceanTerritory,
    HongKong,
    Macao,
    CookIslands,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    AmericanSamoa,
    Guam,
    Indonesia,
    Singapore,
    Thailand,
    Philippines,
    Malaysia,
    SaintBarthelemy,
    SaintMartin,
    SaintPierreAndMiquelon,
    China,
    Afghanistan,
    Kazakhstan,
    Kyrgyzstan,
    Pakistan,
    Tajikistan,
    Turkmenistan,
    Uzbekistan,
    UAE,
    India,
    Egypt,
    Oman,
    Qatar,
    Kuwait,
    SaudiArabia,
    Syria,
    Bahrain,
    Jordan,
    Iran,
    Iraq,
    Israel,
    Lebanon,
    Palestine,
    Yemen,
    SanMarino,
    VaticanCity,
    Bermuda,
    FrenchPolynesia,
    Reunion,
    Mayotte,
    NewCaledonia,
    WallisAndFutuna,
    Nigeria,
    Angola,
    Ghana,
    Togo,
    Benin,
    BurkinaFaso,
    CoteDIvoire,
    Liberia,
    SierraLeone,
    Guinea,
    GuineaBissau,
    Senegal,
    TheGambia,
    CapeVerde,
    SaintHelena,
    Moldova,
    Ukraine,
    Cameroon,
    CentralAfricanRepublic,
    DemocraticRepublicOfTheCongo,
    RepublicOfTheCongo,
    EquatorialGuinea,
    Gabon,
    SaoTomeAndPrincipe,
    Algeria,
    Ethiopia,
    Libya,
    Morocco,
    SouthSudan,
    Tunisia,
    SahrawiArabDemocraticRepublic,
    Somaliland,
    Burundi,
    Comoros,
    Kenya,
    Madagascar,
    Malawi,
    Mauritius,
    Rwanda,
    Seychelles,
    Tanzania,
    Uganda,
    FrenchSouthernAndAntarcticLands,
    PitcairnIslands,
    BritishAntarcticTerritory,
    SouthGeorgiaAndTheSouthSandwichIslands,
    FederatedStatesOfMicronesia,
    Fiji,
    Kiribati,
    MarshallIslands,
    Nauru,
    Palau,
    PapuaNewGuinea,
    Samoa,
    SolomonIslands,
    Tokelau,
    Tonga,
    Tuvalu,
    Vanuatu,
    ChristmasIsland,
    CocosKeelingIslands,
    PuertoRico,
    Greenland,
    NotSet,
}

impl std::fmt::Display for Country {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Country::Japan => write!(f, "Japan"),
            Country::Antarctica => write!(f, "Antarctica"),
            Country::Bonaire => write!(f, "Bonaire"),
            Country::FalklandIslands => write!(f, "Falkland Islands"),
            Country::Saba => write!(f, "Saba"),
            Country::SintEustatius => write!(f, "Sint Eustatius"),
            Country::SintMaarten => write!(f, "Sint Maarten"),
            Country::Anguilla => write!(f, "Anguilla"),
            Country::AntiguaAndBarbuda => write!(f, "Antigua and Barbuda"),
            Country::Argentina => write!(f, "Argentina"),
            Country::Aruba => write!(f, "Aruba"),
            Country::Bahamas => write!(f, "Bahamas"),
            Country::Barbados => write!(f, "Barbados"),
            Country::Belize => write!(f, "Belize"),
            Country::Bolivia => write!(f, "Bolivia"),
            Country::Brazil => write!(f, "Brazil"),
            Country::BritishVirginIslands => write!(f, "British Virgin Islands"),
            Country::Canada => write!(f, "Canada"),
            Country::CaymanIslands => write!(f, "Cayman Islands"),
            Country::Chile => write!(f, "Chile"),
            Country::Colombia => write!(f, "Colombia"),
            Country::CostaRica => write!(f, "Costa Rica"),
            Country::Dominica => write!(f, "Dominica"),
            Country::DominicanRepublic => write!(f, "Dominican Republic"),
            Country::Ecuador => write!(f, "Ecuador"),
            Country::ElSalvador => write!(f, "El Salvador"),
            Country::FrenchGuiana => write!(f, "French Guiana"),
            Country::Grenada => write!(f, "Grenada"),
            Country::Guadeloupe => write!(f, "Guadeloupe"),
            Country::Guatemala => write!(f, "Guatemala"),
            Country::Guyana => write!(f, "Guyana"),
            Country::Haiti => write!(f, "Haiti"),
            Country::Honduras => write!(f, "Honduras"),
            Country::Jamaica => write!(f, "Jamaica"),
            Country::Martinique => write!(f, "Martinique"),
            Country::Mexico => write!(f, "Mexico"),
            Country::Montserrat => write!(f, "Montserrat"),
            Country::Curacao => write!(f, "Curaçao"),
            Country::Nicaragua => write!(f, "Nicaragua"),
            Country::Panama => write!(f, "Panama"),
            Country::Paraguay => write!(f, "Paraguay"),
            Country::Peru => write!(f, "Peru"),
            Country::StKittsAndNevis => write!(f, "St. Kitts and Nevis"),
            Country::StLucia => write!(f, "St. Lucia"),
            Country::StVincentAndTheGrenadines => write!(f, "St. Vincent and the Grenadines"),
            Country::Suriname => write!(f, "Suriname"),
            Country::TrinidadAndTobago => write!(f, "Trinidad and Tobago"),
            Country::TurksAndCaicosIslands => write!(f, "Turks and Caicos Islands"),
            Country::UnitedStates => write!(f, "United States"),
            Country::Uruguay => write!(f, "Uruguay"),
            Country::USVirginIslands => write!(f, "US Virgin Islands"),
            Country::Venezuela => write!(f, "Venezuela"),
            Country::Armenia => write!(f, "Armenia"),
            Country::Belarus => write!(f, "Belarus"),
            Country::Georgia => write!(f, "Georgia"),
            Country::Kosovo => write!(f, "Kosovo"),
            Country::Abkhazia => write!(f, "Abkhazia"),
            Country::Artsakh => write!(f, "Artsakh"),
            Country::NorthernCyprus => write!(f, "Northern Cyprus"),
            Country::SouthOssetia => write!(f, "South Ossetia"),
            Country::Transnistria => write!(f, "Transnistria"),
            Country::Aland => write!(f, "Åland"),
            Country::FaroeIslands => write!(f, "Faroe Islands"),
            Country::Albania => write!(f, "Albania"),
            Country::Australia => write!(f, "Australia"),
            Country::Austria => write!(f, "Austria"),
            Country::Belgium => write!(f, "Belgium"),
            Country::BosniaAndHerzegovina => write!(f, "Bosnia & Herzegovina"),
            Country::Botswana => write!(f, "Botswana"),
            Country::Bulgaria => write!(f, "Bulgaria"),
            Country::Croatia => write!(f, "Croatia"),
            Country::Cyprus => write!(f, "Cyprus"),
            Country::Czechia => write!(f, "Czechia"),
            Country::Denmark => write!(f, "Denmark"),
            Country::Estonia => write!(f, "Estonia"),
            Country::Finland => write!(f, "Finland"),
            Country::France => write!(f, "France"),
            Country::Germany => write!(f, "Germany"),
            Country::Greece => write!(f, "Greece"),
            Country::Hungary => write!(f, "Hungary"),
            Country::Iceland => write!(f, "Iceland"),
            Country::Ireland => write!(f, "Ireland"),
            Country::Italy => write!(f, "Italy"),
            Country::Latvia => write!(f, "Latvia"),
            Country::Lesotho => write!(f, "Lesotho"),
            Country::Liechtenstein => write!(f, "Liechtenstein"),
            Country::Lithuania => write!(f, "Lithuania"),
            Country::Luxembourg => write!(f, "Luxembourg"),
            Country::NorthMacedonia => write!(f, "North Macedonia"),
            Country::Malta => write!(f, "Malta"),
            Country::Montenegro => write!(f, "Montenegro"),
            Country::Mozambique => write!(f, "Mozambique"),
            Country::Namibia => write!(f, "Namibia"),
            Country::Netherlands => write!(f, "Netherlands"),
            Country::NewZealand => write!(f, "New Zealand"),
            Country::Norway => write!(f, "Norway"),
            Country::Poland => write!(f, "Poland"),
            Country::Portugal => write!(f, "Portugal"),
            Country::Romania => write!(f, "Romania"),
            Country::Russia => write!(f, "Russia"),
            Country::Serbia => write!(f, "Serbia"),
            Country::Slovakia => write!(f, "Slovakia"),
            Country::Slovenia => write!(f, "Slovenia"),
            Country::SouthAfrica => write!(f, "South Africa"),
            Country::Spain => write!(f, "Spain"),
            Country::Eswatini => write!(f, "Eswatini"),
            Country::Sweden => write!(f, "Sweden"),
            Country::Switzerland => write!(f, "Switzerland"),
            Country::Turkey => write!(f, "Turkey"),
            Country::UnitedKingdom => write!(f, "United Kingdom"),
            Country::Zambia => write!(f, "Zambia"),
            Country::Zimbabwe => write!(f, "Zimbabwe"),
            Country::Azerbaijan => write!(f, "Azerbaijan"),
            Country::Mauritania => write!(f, "Mauritania"),
            Country::Mali => write!(f, "Mali"),
            Country::Niger => write!(f, "Niger"),
            Country::Chad => write!(f, "Chad"),
            Country::Sudan => write!(f, "Sudan"),
            Country::Eritrea => write!(f, "Eritrea"),
            Country::Djibouti => write!(f, "Djibouti"),
            Country::Somalia => write!(f, "Somalia"),
            Country::Andorra => write!(f, "Andorra"),
            Country::Gibraltar => write!(f, "Gibraltar"),
            Country::Guernsey => write!(f, "Guernsey"),
            Country::IsleOfMan => write!(f, "Isle of Man"),
            Country::Jersey => write!(f, "Jersey"),
            Country::Monaco => write!(f, "Monaco"),
            Country::Taiwan => write!(f, "Taiwan"),
            Country::Cambodia => write!(f, "Cambodia"),
            Country::Laos => write!(f, "Laos"),
            Country::Mongolia => write!(f, "Mongolia"),
            Country::Myanmar => write!(f, "Myanmar"),
            Country::Nepal => write!(f, "Nepal"),
            Country::Vietnam => write!(f, "Vietnam"),
            Country::NorthKorea => write!(f, "North Korea"),
            Country::SouthKorea => write!(f, "South Korea"),
            Country::Bangladesh => write!(f, "Bangladesh"),
            Country::Bhutan => write!(f, "Bhutan"),
            Country::Brunei => write!(f, "Brunei"),
            Country::Maldives => write!(f, "Maldives"),
            Country::SriLanka => write!(f, "Sri Lanka"),
            Country::TimorLeste => write!(f, "Timor-Leste"),
            Country::BritishIndianOceanTerritory => write!(f, "British Indian Ocean Territory"),
            Country::HongKong => write!(f, "Hong Kong"),
            Country::Macao => write!(f, "Macao"),
            Country::CookIslands => write!(f, "Cook Islands"),
            Country::Niue => write!(f, "Niue"),
            Country::NorfolkIsland => write!(f, "Norfolk Island"),
            Country::NorthernMarianaIslands => write!(f, "Northern Mariana Islands"),
            Country::AmericanSamoa => write!(f, "American Samoa"),
            Country::Guam => write!(f, "Guam"),
            Country::Indonesia => write!(f, "Indonesia"),
            Country::Singapore => write!(f, "Singapore"),
            Country::Thailand => write!(f, "Thailand"),
            Country::Philippines => write!(f, "Philippines"),
            Country::Malaysia => write!(f, "Malaysia"),
            Country::SaintBarthelemy => write!(f, "Saint Barthélemy"),
            Country::SaintMartin => write!(f, "Saint Martin"),
            Country::SaintPierreAndMiquelon => write!(f, "Saint Pierre and Miquelon"),
            Country::China => write!(f, "China"),
            Country::Afghanistan => write!(f, "Afghanistan"),
            Country::Kazakhstan => write!(f, "Kazakhstan"),
            Country::Kyrgyzstan => write!(f, "Kyrgyzstan"),
            Country::Pakistan => write!(f, "Pakistan"),
            Country::Tajikistan => write!(f, "Tajikistan"),
            Country::Turkmenistan => write!(f, "Turkmenistan"),
            Country::Uzbekistan => write!(f, "Uzbekistan"),
            Country::UAE => write!(f, "U.A.E"),
            Country::India => write!(f, "India"),
            Country::Egypt => write!(f, "Egypt"),
            Country::Oman => write!(f, "Oman"),
            Country::Qatar => write!(f, "Qatar"),
            Country::Kuwait => write!(f, "Kuwait"),
            Country::SaudiArabia => write!(f, "Saudi Arabia"),
            Country::Syria => write!(f, "Syria"),
            Country::Bahrain => write!(f, "Bahrain"),
            Country::Jordan => write!(f, "Jordan"),
            Country::Iran => write!(f, "Iran"),
            Country::Iraq => write!(f, "Iraq"),
            Country::Israel => write!(f, "Israel"),
            Country::Lebanon => write!(f, "Lebanon"),
            Country::Palestine => write!(f, "Palestine"),
            Country::Yemen => write!(f, "Yemen"),
            Country::SanMarino => write!(f, "San Marino"),
            Country::VaticanCity => write!(f, "Vatican City"),
            Country::Bermuda => write!(f, "Bermuda"),
            Country::FrenchPolynesia => write!(f, "French Polynesia"),
            Country::Reunion => write!(f, "Réunion"),
            Country::Mayotte => write!(f, "Mayotte"),
            Country::NewCaledonia => write!(f, "New Caledonia"),
            Country::WallisAndFutuna => write!(f, "Wallis and Futuna"),
            Country::Nigeria => write!(f, "Nigeria"),
            Country::Angola => write!(f, "Angola"),
            Country::Ghana => write!(f, "Ghana"),
            Country::Togo => write!(f, "Togo"),
            Country::Benin => write!(f, "Benin"),
            Country::BurkinaFaso => write!(f, "Burkina Faso"),
            Country::CoteDIvoire => write!(f, "Côte d'Ivoire"),
            Country::Liberia => write!(f, "Liberia"),
            Country::SierraLeone => write!(f, "Sierra Leone"),
            Country::Guinea => write!(f, "Guinea"),
            Country::GuineaBissau => write!(f, "Guinea-Bissau"),
            Country::Senegal => write!(f, "Senegal"),
            Country::TheGambia => write!(f, "The Gambia"),
            Country::CapeVerde => write!(f, "Cape Verde"),
            Country::SaintHelena => write!(f, "Saint Helena, Ascension and Tristan da Cunha"),
            Country::Moldova => write!(f, "Moldova"),
            Country::Ukraine => write!(f, "Ukraine"),
            Country::Cameroon => write!(f, "Cameroon"),
            Country::CentralAfricanRepublic => write!(f, "Central African Republic"),
            Country::DemocraticRepublicOfTheCongo => write!(f, "Democratic Republic of the Congo"),
            Country::RepublicOfTheCongo => write!(f, "Republic of the Congo"),
            Country::EquatorialGuinea => write!(f, "Equatorial Guinea"),
            Country::Gabon => write!(f, "Gabon"),
            Country::SaoTomeAndPrincipe => write!(f, "São Tomé and Príncipe"),
            Country::Algeria => write!(f, "Algeria"),
            Country::Ethiopia => write!(f, "Ethiopia"),
            Country::Libya => write!(f, "Libya"),
            Country::Morocco => write!(f, "Morocco"),
            Country::SouthSudan => write!(f, "South Sudan"),
            Country::Tunisia => write!(f, "Tunisia"),
            Country::SahrawiArabDemocraticRepublic => write!(f, "Sahrawi Arab Democratic Republic"),
            Country::Somaliland => write!(f, "Somaliland"),
            Country::Burundi => write!(f, "Burundi"),
            Country::Comoros => write!(f, "Comoros"),
            Country::Kenya => write!(f, "Kenya"),
            Country::Madagascar => write!(f, "Madagascar"),
            Country::Malawi => write!(f, "Malawi"),
            Country::Mauritius => write!(f, "Mauritius"),
            Country::Rwanda => write!(f, "Rwanda"),
            Country::Seychelles => write!(f, "Seychelles"),
            Country::Tanzania => write!(f, "Tanzania"),
            Country::Uganda => write!(f, "Uganda"),
            Country::FrenchSouthernAndAntarcticLands => {
                write!(f, "French Southern and Antarctic Lands")
            }
            Country::PitcairnIslands => write!(f, "Pitcairn Islands"),
            Country::BritishAntarcticTerritory => write!(f, "British Antarctic Territory"),
            Country::SouthGeorgiaAndTheSouthSandwichIslands => {
                write!(f, "South Georgia and the South Sandwich Islands")
            }
            Country::FederatedStatesOfMicronesia => write!(f, "Federated States of Micronesia"),
            Country::Fiji => write!(f, "Fiji"),
            Country::Kiribati => write!(f, "Kiribati"),
            Country::MarshallIslands => write!(f, "Marshall Islands"),
            Country::Nauru => write!(f, "Nauru"),
            Country::Palau => write!(f, "Palau"),
            Country::PapuaNewGuinea => write!(f, "Papua New Guinea"),
            Country::Samoa => write!(f, "Samoa"),
            Country::SolomonIslands => write!(f, "Solomon Islands"),
            Country::Tokelau => write!(f, "Tokelau"),
            Country::Tonga => write!(f, "Tonga"),
            Country::Tuvalu => write!(f, "Tuvalu"),
            Country::Vanuatu => write!(f, "Vanuatu"),
            Country::ChristmasIsland => write!(f, "Christmas Island"),
            Country::CocosKeelingIslands => write!(f, "Cocos (Keeling) Islands"),
            Country::PuertoRico => write!(f, "Puerto Rico"),
            Country::Greenland => write!(f, "Greenland"),
            Country::NotSet => write!(f, "Not Set"),
        }
    }
}

impl From<Country> for u8 {
    fn from(country: Country) -> u8 {
        match country {
            Country::Japan => 0x01,
            Country::Antarctica => 0x02,
            Country::Bonaire => 0x03,
            Country::FalklandIslands => 0x04,
            Country::Saba => 0x05,
            Country::SintEustatius => 0x06,
            Country::SintMaarten => 0x07,
            Country::Anguilla => 0x08,
            Country::AntiguaAndBarbuda => 0x09,
            Country::Argentina => 0x0A,
            Country::Aruba => 0x0B,
            Country::Bahamas => 0x0C,
            Country::Barbados => 0x0D,
            Country::Belize => 0x0E,
            Country::Bolivia => 0x0F,
            Country::Brazil => 0x10,
            Country::BritishVirginIslands => 0x11,
            Country::Canada => 0x12,
            Country::CaymanIslands => 0x13,
            Country::Chile => 0x14,
            Country::Colombia => 0x15,
            Country::CostaRica => 0x16,
            Country::Dominica => 0x17,
            Country::DominicanRepublic => 0x18,
            Country::Ecuador => 0x19,
            Country::ElSalvador => 0x1A,
            Country::FrenchGuiana => 0x1B,
            Country::Grenada => 0x1C,
            Country::Guadeloupe => 0x1D,
            Country::Guatemala => 0x1E,
            Country::Guyana => 0x1F,
            Country::Haiti => 0x20,
            Country::Honduras => 0x21,
            Country::Jamaica => 0x22,
            Country::Martinique => 0x23,
            Country::Mexico => 0x24,
            Country::Montserrat => 0x25,
            Country::Curacao => 0x26,
            Country::Nicaragua => 0x27,
            Country::Panama => 0x28,
            Country::Paraguay => 0x29,
            Country::Peru => 0x2A,
            Country::StKittsAndNevis => 0x2B,
            Country::StLucia => 0x2C,
            Country::StVincentAndTheGrenadines => 0x2D,
            Country::Suriname => 0x2E,
            Country::TrinidadAndTobago => 0x2F,
            Country::TurksAndCaicosIslands => 0x30,
            Country::UnitedStates => 0x31,
            Country::Uruguay => 0x32,
            Country::USVirginIslands => 0x33,
            Country::Venezuela => 0x34,
            Country::Armenia => 0x35,
            Country::Belarus => 0x36,
            Country::Georgia => 0x37,
            Country::Kosovo => 0x38,
            Country::Abkhazia => 0x39,
            Country::Artsakh => 0x3A,
            Country::NorthernCyprus => 0x3B,
            Country::SouthOssetia => 0x3C,
            Country::Transnistria => 0x3D,
            Country::Aland => 0x3E,
            Country::FaroeIslands => 0x3F,
            Country::Albania => 0x40,
            Country::Australia => 0x41,
            Country::Austria => 0x42,
            Country::Belgium => 0x43,
            Country::BosniaAndHerzegovina => 0x44,
            Country::Botswana => 0x45,
            Country::Bulgaria => 0x46,
            Country::Croatia => 0x47,
            Country::Cyprus => 0x48,
            Country::Czechia => 0x49,
            Country::Denmark => 0x4A,
            Country::Estonia => 0x4B,
            Country::Finland => 0x4C,
            Country::France => 0x4D,
            Country::Germany => 0x4E,
            Country::Greece => 0x4F,
            Country::Hungary => 0x50,
            Country::Iceland => 0x51,
            Country::Ireland => 0x52,
            Country::Italy => 0x53,
            Country::Latvia => 0x54,
            Country::Lesotho => 0x55,
            Country::Liechtenstein => 0x56,
            Country::Lithuania => 0x57,
            Country::Luxembourg => 0x58,
            Country::NorthMacedonia => 0x59,
            Country::Malta => 0x5A,
            Country::Montenegro => 0x5B,
            Country::Mozambique => 0x5C,
            Country::Namibia => 0x5D,
            Country::Netherlands => 0x5E,
            Country::NewZealand => 0x5F,
            Country::Norway => 0x60,
            Country::Poland => 0x61,
            Country::Portugal => 0x62,
            Country::Romania => 0x63,
            Country::Russia => 0x64,
            Country::Serbia => 0x65,
            Country::Slovakia => 0x66,
            Country::Slovenia => 0x67,
            Country::SouthAfrica => 0x68,
            Country::Spain => 0x69,
            Country::Eswatini => 0x6A,
            Country::Sweden => 0x6B,
            Country::Switzerland => 0x6C,
            Country::Turkey => 0x6D,
            Country::UnitedKingdom => 0x6E,
            Country::Zambia => 0x6F,
            Country::Zimbabwe => 0x70,
            Country::Azerbaijan => 0x71,
            Country::Mauritania => 0x72,
            Country::Mali => 0x73,
            Country::Niger => 0x74,
            Country::Chad => 0x75,
            Country::Sudan => 0x76,
            Country::Eritrea => 0x77,
            Country::Djibouti => 0x78,
            Country::Somalia => 0x79,
            Country::Andorra => 0x7A,
            Country::Gibraltar => 0x7B,
            Country::Guernsey => 0x7C,
            Country::IsleOfMan => 0x7D,
            Country::Jersey => 0x7E,
            Country::Monaco => 0x7F,
            Country::Taiwan => 0x80,
            Country::Cambodia => 0x81,
            Country::Laos => 0x82,
            Country::Mongolia => 0x83,
            Country::Myanmar => 0x84,
            Country::Nepal => 0x85,
            Country::Vietnam => 0x86,
            Country::NorthKorea => 0x87,
            Country::SouthKorea => 0x88,
            Country::Bangladesh => 0x89,
            Country::Bhutan => 0x8A,
            Country::Brunei => 0x8B,
            Country::Maldives => 0x8C,
            Country::SriLanka => 0x8D,
            Country::TimorLeste => 0x8E,
            Country::BritishIndianOceanTerritory => 0x8F,
            Country::HongKong => 0x90,
            Country::Macao => 0x91,
            Country::CookIslands => 0x92,
            Country::Niue => 0x93,
            Country::NorfolkIsland => 0x94,
            Country::NorthernMarianaIslands => 0x95,
            Country::AmericanSamoa => 0x96,
            Country::Guam => 0x97,
            Country::Indonesia => 0x98,
            Country::Singapore => 0x99,
            Country::Thailand => 0x9A,
            Country::Philippines => 0x9B,
            Country::Malaysia => 0x9C,
            Country::SaintBarthelemy => 0x9D,
            Country::SaintMartin => 0x9E,
            Country::SaintPierreAndMiquelon => 0x9F,
            Country::China => 0xA0,
            Country::Afghanistan => 0xA1,
            Country::Kazakhstan => 0xA2,
            Country::Kyrgyzstan => 0xA3,
            Country::Pakistan => 0xA4,
            Country::Tajikistan => 0xA5,
            Country::Turkmenistan => 0xA6,
            Country::Uzbekistan => 0xA7,
            Country::UAE => 0xA8,
            Country::India => 0xA9,
            Country::Egypt => 0xAA,
            Country::Oman => 0xAB,
            Country::Qatar => 0xAC,
            Country::Kuwait => 0xAD,
            Country::SaudiArabia => 0xAE,
            Country::Syria => 0xAF,
            Country::Bahrain => 0xB0,
            Country::Jordan => 0xB1,
            Country::Iran => 0xB2,
            Country::Iraq => 0xB3,
            Country::Israel => 0xB4,
            Country::Lebanon => 0xB5,
            Country::Palestine => 0xB6,
            Country::Yemen => 0xB7,
            Country::SanMarino => 0xB8,
            Country::VaticanCity => 0xB9,
            Country::Bermuda => 0xBA,
            Country::FrenchPolynesia => 0xBB,
            Country::Reunion => 0xBC,
            Country::Mayotte => 0xBD,
            Country::NewCaledonia => 0xBE,
            Country::WallisAndFutuna => 0xBF,
            Country::Nigeria => 0xC0,
            Country::Angola => 0xC1,
            Country::Ghana => 0xC2,
            Country::Togo => 0xC3,
            Country::Benin => 0xC4,
            Country::BurkinaFaso => 0xC5,
            Country::CoteDIvoire => 0xC6,
            Country::Liberia => 0xC7,
            Country::SierraLeone => 0xC8,
            Country::Guinea => 0xC9,
            Country::GuineaBissau => 0xCA,
            Country::Senegal => 0xCB,
            Country::TheGambia => 0xCC,
            Country::CapeVerde => 0xCD,
            Country::SaintHelena => 0xCE,
            Country::Moldova => 0xCF,
            Country::Ukraine => 0xD0,
            Country::Cameroon => 0xD1,
            Country::CentralAfricanRepublic => 0xD2,
            Country::DemocraticRepublicOfTheCongo => 0xD3,
            Country::RepublicOfTheCongo => 0xD4,
            Country::EquatorialGuinea => 0xD5,
            Country::Gabon => 0xD6,
            Country::SaoTomeAndPrincipe => 0xD7,
            Country::Algeria => 0xD8,
            Country::Ethiopia => 0xD9,
            Country::Libya => 0xDA,
            Country::Morocco => 0xDB,
            Country::SouthSudan => 0xDC,
            Country::Tunisia => 0xDD,
            Country::SahrawiArabDemocraticRepublic => 0xDE,
            Country::Somaliland => 0xDF,
            Country::Burundi => 0xE0,
            Country::Comoros => 0xE1,
            Country::Kenya => 0xE2,
            Country::Madagascar => 0xE3,
            Country::Malawi => 0xE4,
            Country::Mauritius => 0xE5,
            Country::Rwanda => 0xE6,
            Country::Seychelles => 0xE7,
            Country::Tanzania => 0xE8,
            Country::Uganda => 0xE9,
            Country::FrenchSouthernAndAntarcticLands => 0xEA,
            Country::PitcairnIslands => 0xEB,
            Country::BritishAntarcticTerritory => 0xEC,
            Country::SouthGeorgiaAndTheSouthSandwichIslands => 0xED,
            Country::FederatedStatesOfMicronesia => 0xEE,
            Country::Fiji => 0xEF,
            Country::Kiribati => 0xF0,
            Country::MarshallIslands => 0xF1,
            Country::Nauru => 0xF2,
            Country::Palau => 0xF3,
            Country::PapuaNewGuinea => 0xF4,
            Country::Samoa => 0xF5,
            Country::SolomonIslands => 0xF6,
            Country::Tokelau => 0xF7,
            Country::Tonga => 0xF8,
            Country::Tuvalu => 0xF9,
            Country::Vanuatu => 0xFA,
            Country::ChristmasIsland => 0xFB,
            Country::CocosKeelingIslands => 0xFC,
            Country::PuertoRico => 0xFD,
            Country::Greenland => 0xFE,
            Country::NotSet => 0xFF,
        }
    }
}

impl TryFrom<u8> for Country {
    type Error = CountryError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x01 => Ok(Country::Japan),
            0x02 => Ok(Country::Antarctica),
            0x03 => Ok(Country::Bonaire),
            0x04 => Ok(Country::FalklandIslands),
            0x05 => Ok(Country::Saba),
            0x06 => Ok(Country::SintEustatius),
            0x07 => Ok(Country::SintMaarten),
            0x08 => Ok(Country::Anguilla),
            0x09 => Ok(Country::AntiguaAndBarbuda),
            0x0A => Ok(Country::Argentina),
            0x0B => Ok(Country::Aruba),
            0x0C => Ok(Country::Bahamas),
            0x0D => Ok(Country::Barbados),
            0x0E => Ok(Country::Belize),
            0x0F => Ok(Country::Bolivia),
            0x10 => Ok(Country::Brazil),
            0x11 => Ok(Country::BritishVirginIslands),
            0x12 => Ok(Country::Canada),
            0x13 => Ok(Country::CaymanIslands),
            0x14 => Ok(Country::Chile),
            0x15 => Ok(Country::Colombia),
            0x16 => Ok(Country::CostaRica),
            0x17 => Ok(Country::Dominica),
            0x18 => Ok(Country::DominicanRepublic),
            0x19 => Ok(Country::Ecuador),
            0x1A => Ok(Country::ElSalvador),
            0x1B => Ok(Country::FrenchGuiana),
            0x1C => Ok(Country::Grenada),
            0x1D => Ok(Country::Guadeloupe),
            0x1E => Ok(Country::Guatemala),
            0x1F => Ok(Country::Guyana),
            0x20 => Ok(Country::Haiti),
            0x21 => Ok(Country::Honduras),
            0x22 => Ok(Country::Jamaica),
            0x23 => Ok(Country::Martinique),
            0x24 => Ok(Country::Mexico),
            0x25 => Ok(Country::Montserrat),
            0x26 => Ok(Country::Curacao),
            0x27 => Ok(Country::Nicaragua),
            0x28 => Ok(Country::Panama),
            0x29 => Ok(Country::Paraguay),
            0x2A => Ok(Country::Peru),
            0x2B => Ok(Country::StKittsAndNevis),
            0x2C => Ok(Country::StLucia),
            0x2D => Ok(Country::StVincentAndTheGrenadines),
            0x2E => Ok(Country::Suriname),
            0x2F => Ok(Country::TrinidadAndTobago),
            0x30 => Ok(Country::TurksAndCaicosIslands),
            0x31 => Ok(Country::UnitedStates),
            0x32 => Ok(Country::Uruguay),
            0x33 => Ok(Country::USVirginIslands),
            0x34 => Ok(Country::Venezuela),
            0x35 => Ok(Country::Armenia),
            0x36 => Ok(Country::Belarus),
            0x37 => Ok(Country::Georgia),
            0x38 => Ok(Country::Kosovo),
            0x39 => Ok(Country::Abkhazia),
            0x3A => Ok(Country::Artsakh),
            0x3B => Ok(Country::NorthernCyprus),
            0x3C => Ok(Country::SouthOssetia),
            0x3D => Ok(Country::Transnistria),
            0x3E => Ok(Country::Aland),
            0x3F => Ok(Country::FaroeIslands),
            0x40 => Ok(Country::Albania),
            0x41 => Ok(Country::Australia),
            0x42 => Ok(Country::Austria),
            0x43 => Ok(Country::Belgium),
            0x44 => Ok(Country::BosniaAndHerzegovina),
            0x45 => Ok(Country::Botswana),
            0x46 => Ok(Country::Bulgaria),
            0x47 => Ok(Country::Croatia),
            0x48 => Ok(Country::Cyprus),
            0x49 => Ok(Country::Czechia),
            0x4A => Ok(Country::Denmark),
            0x4B => Ok(Country::Estonia),
            0x4C => Ok(Country::Finland),
            0x4D => Ok(Country::France),
            0x4E => Ok(Country::Germany),
            0x4F => Ok(Country::Greece),
            0x50 => Ok(Country::Hungary),
            0x51 => Ok(Country::Iceland),
            0x52 => Ok(Country::Ireland),
            0x53 => Ok(Country::Italy),
            0x54 => Ok(Country::Latvia),
            0x55 => Ok(Country::Lesotho),
            0x56 => Ok(Country::Liechtenstein),
            0x57 => Ok(Country::Lithuania),
            0x58 => Ok(Country::Luxembourg),
            0x59 => Ok(Country::NorthMacedonia),
            0x5A => Ok(Country::Malta),
            0x5B => Ok(Country::Montenegro),
            0x5C => Ok(Country::Mozambique),
            0x5D => Ok(Country::Namibia),
            0x5E => Ok(Country::Netherlands),
            0x5F => Ok(Country::NewZealand),
            0x60 => Ok(Country::Norway),
            0x61 => Ok(Country::Poland),
            0x62 => Ok(Country::Portugal),
            0x63 => Ok(Country::Romania),
            0x64 => Ok(Country::Russia),
            0x65 => Ok(Country::Serbia),
            0x66 => Ok(Country::Slovakia),
            0x67 => Ok(Country::Slovenia),
            0x68 => Ok(Country::SouthAfrica),
            0x69 => Ok(Country::Spain),
            0x6A => Ok(Country::Eswatini),
            0x6B => Ok(Country::Sweden),
            0x6C => Ok(Country::Switzerland),
            0x6D => Ok(Country::Turkey),
            0x6E => Ok(Country::UnitedKingdom),
            0x6F => Ok(Country::Zambia),
            0x70 => Ok(Country::Zimbabwe),
            0x71 => Ok(Country::Azerbaijan),
            0x72 => Ok(Country::Mauritania),
            0x73 => Ok(Country::Mali),
            0x74 => Ok(Country::Niger),
            0x75 => Ok(Country::Chad),
            0x76 => Ok(Country::Sudan),
            0x77 => Ok(Country::Eritrea),
            0x78 => Ok(Country::Djibouti),
            0x79 => Ok(Country::Somalia),
            0x7A => Ok(Country::Andorra),
            0x7B => Ok(Country::Gibraltar),
            0x7C => Ok(Country::Guernsey),
            0x7D => Ok(Country::IsleOfMan),
            0x7E => Ok(Country::Jersey),
            0x7F => Ok(Country::Monaco),
            0x80 => Ok(Country::Taiwan),
            0x81 => Ok(Country::Cambodia),
            0x82 => Ok(Country::Laos),
            0x83 => Ok(Country::Mongolia),
            0x84 => Ok(Country::Myanmar),
            0x85 => Ok(Country::Nepal),
            0x86 => Ok(Country::Vietnam),
            0x87 => Ok(Country::NorthKorea),
            0x88 => Ok(Country::SouthKorea),
            0x89 => Ok(Country::Bangladesh),
            0x8A => Ok(Country::Bhutan),
            0x8B => Ok(Country::Brunei),
            0x8C => Ok(Country::Maldives),
            0x8D => Ok(Country::SriLanka),
            0x8E => Ok(Country::TimorLeste),
            0x8F => Ok(Country::BritishIndianOceanTerritory),
            0x90 => Ok(Country::HongKong),
            0x91 => Ok(Country::Macao),
            0x92 => Ok(Country::CookIslands),
            0x93 => Ok(Country::Niue),
            0x94 => Ok(Country::NorfolkIsland),
            0x95 => Ok(Country::NorthernMarianaIslands),
            0x96 => Ok(Country::AmericanSamoa),
            0x97 => Ok(Country::Guam),
            0x98 => Ok(Country::Indonesia),
            0x99 => Ok(Country::Singapore),
            0x9A => Ok(Country::Thailand),
            0x9B => Ok(Country::Philippines),
            0x9C => Ok(Country::Malaysia),
            0x9D => Ok(Country::SaintBarthelemy),
            0x9E => Ok(Country::SaintMartin),
            0x9F => Ok(Country::SaintPierreAndMiquelon),
            0xA0 => Ok(Country::China),
            0xA1 => Ok(Country::Afghanistan),
            0xA2 => Ok(Country::Kazakhstan),
            0xA3 => Ok(Country::Kyrgyzstan),
            0xA4 => Ok(Country::Pakistan),
            0xA5 => Ok(Country::Tajikistan),
            0xA6 => Ok(Country::Turkmenistan),
            0xA7 => Ok(Country::Uzbekistan),
            0xA8 => Ok(Country::UAE),
            0xA9 => Ok(Country::India),
            0xAA => Ok(Country::Egypt),
            0xAB => Ok(Country::Oman),
            0xAC => Ok(Country::Qatar),
            0xAD => Ok(Country::Kuwait),
            0xAE => Ok(Country::SaudiArabia),
            0xAF => Ok(Country::Syria),
            0xB0 => Ok(Country::Bahrain),
            0xB1 => Ok(Country::Jordan),
            0xB2 => Ok(Country::Iran),
            0xB3 => Ok(Country::Iraq),
            0xB4 => Ok(Country::Israel),
            0xB5 => Ok(Country::Lebanon),
            0xB6 => Ok(Country::Palestine),
            0xB7 => Ok(Country::Yemen),
            0xB8 => Ok(Country::SanMarino),
            0xB9 => Ok(Country::VaticanCity),
            0xBA => Ok(Country::Bermuda),
            0xBB => Ok(Country::FrenchPolynesia),
            0xBC => Ok(Country::Reunion),
            0xBD => Ok(Country::Mayotte),
            0xBE => Ok(Country::NewCaledonia),
            0xBF => Ok(Country::WallisAndFutuna),
            0xC0 => Ok(Country::Nigeria),
            0xC1 => Ok(Country::Angola),
            0xC2 => Ok(Country::Ghana),
            0xC3 => Ok(Country::Togo),
            0xC4 => Ok(Country::Benin),
            0xC5 => Ok(Country::BurkinaFaso),
            0xC6 => Ok(Country::CoteDIvoire),
            0xC7 => Ok(Country::Liberia),
            0xC8 => Ok(Country::SierraLeone),
            0xC9 => Ok(Country::Guinea),
            0xCA => Ok(Country::GuineaBissau),
            0xCB => Ok(Country::Senegal),
            0xCC => Ok(Country::TheGambia),
            0xCD => Ok(Country::CapeVerde),
            0xCE => Ok(Country::SaintHelena),
            0xCF => Ok(Country::Moldova),
            0xD0 => Ok(Country::Ukraine),
            0xD1 => Ok(Country::Cameroon),
            0xD2 => Ok(Country::CentralAfricanRepublic),
            0xD3 => Ok(Country::DemocraticRepublicOfTheCongo),
            0xD4 => Ok(Country::RepublicOfTheCongo),
            0xD5 => Ok(Country::EquatorialGuinea),
            0xD6 => Ok(Country::Gabon),
            0xD7 => Ok(Country::SaoTomeAndPrincipe),
            0xD8 => Ok(Country::Algeria),
            0xD9 => Ok(Country::Ethiopia),
            0xDA => Ok(Country::Libya),
            0xDB => Ok(Country::Morocco),
            0xDC => Ok(Country::SouthSudan),
            0xDD => Ok(Country::Tunisia),
            0xDE => Ok(Country::SahrawiArabDemocraticRepublic),
            0xDF => Ok(Country::Somaliland),
            0xE0 => Ok(Country::Burundi),
            0xE1 => Ok(Country::Comoros),
            0xE2 => Ok(Country::Kenya),
            0xE3 => Ok(Country::Madagascar),
            0xE4 => Ok(Country::Malawi),
            0xE5 => Ok(Country::Mauritius),
            0xE6 => Ok(Country::Rwanda),
            0xE7 => Ok(Country::Seychelles),
            0xE8 => Ok(Country::Tanzania),
            0xE9 => Ok(Country::Uganda),
            0xEA => Ok(Country::FrenchSouthernAndAntarcticLands),
            0xEB => Ok(Country::PitcairnIslands),
            0xEC => Ok(Country::BritishAntarcticTerritory),
            0xED => Ok(Country::SouthGeorgiaAndTheSouthSandwichIslands),
            0xEE => Ok(Country::FederatedStatesOfMicronesia),
            0xEF => Ok(Country::Fiji),
            0xF0 => Ok(Country::Kiribati),
            0xF1 => Ok(Country::MarshallIslands),
            0xF2 => Ok(Country::Nauru),
            0xF3 => Ok(Country::Palau),
            0xF4 => Ok(Country::PapuaNewGuinea),
            0xF5 => Ok(Country::Samoa),
            0xF6 => Ok(Country::SolomonIslands),
            0xF7 => Ok(Country::Tokelau),
            0xF8 => Ok(Country::Tonga),
            0xF9 => Ok(Country::Tuvalu),
            0xFA => Ok(Country::Vanuatu),
            0xFB => Ok(Country::ChristmasIsland),
            0xFC => Ok(Country::CocosKeelingIslands),
            0xFD => Ok(Country::PuertoRico),
            0xFE => Ok(Country::Greenland),
            0xFF => Ok(Country::NotSet),
            _ => Err(CountryError::NonexistentCountry),
        }
    }
}
